metal-toolbox/hollow-serverservice

pkg/api/v1/attribute_list_params.go, pkg/api/v1/attributes.go, pkg/api/v1/router_server.go, pkg/api/v1/router_server_test.go, pkg/api/v1/server_component_list_params.go
This breaks client code compatibility but keeps the API intact so existing clients will continue to work.
=> feat: Add the ability to search attributes with LIKE matches

.github/workflows/lint-test.yml, db/migrations/00008_remove_deleted_at_index.sql, internal/models/crdb_main_test.go
while the addition of the `deleted_at` index migration runs fine, we see issues later when using the client:
```
serverservice-migrate_1  | 2021/09/27 15:19:10 OK    00001_init.sql
serverservice-migrate_1  | 2021/09/27 15:19:11 OK    00002_components_versioned_attrs.sql
serverservice-migrate_1  | 2021/09/27 15:19:11 OK    00003_components_versioned_attrs_indexes.sql
serverservice-migrate_1  | 2021/09/27 15:19:11 OK    00004_server_component_type_slug.sql
serverservice-migrate_1  | 2021/09/27 15:19:12 OK    00005_versioned_attributes_repeat_counter.sql
serverservice-migrate_1  | 2021/09/27 15:19:12 OK    00006_fix_non_nulls.sql
serverservice-migrate_1  | 2021/09/27 15:24:19 OK    00007_deleted_at_attr.sql
serverservice-migrate_1  | 2021/09/27 15:24:19 goose: no migrations to run. current …
```
=> remove deleted_at index

README.md
links to an outside github organization's standards; removed URL until standards within the project are created
=> Remove bad URL in readme

.github/workflows/goreleaser.yml, .gitignore, .goreleaser.yml
This adds keyless signatures powered by cosign to our releases as part
of the goreleaser configuration. It also generates an SBOM using syft.
=> Sign container images and generate SBOM as part of release

.goreleaser.yml
sign-blog takes a file, while we want to sign a container image.
=> cosign: use `sign` and not `sign-blob` for image signing

.goreleaser.yml
This was not needed and might affect builds.
=> Remove unneded parts from `docker_signs` section in goreleaser config

.github/workflows/auto-tag.yml, .github/workflows/goreleaser.yml
This utilizies a GitHub action that automatically cuts releases on the
2nd each month. Note that the release job will fail if there are no
patches to add to a release. This is non-fatal thus we just won't have a
release.
=> Automatically cut releases on the 2nd of each month

renovate.json
This allows us to automatically get updates for container images from
our docker compose files. Even if these are only used for testing, this
is useful as it allows us to get a notion of compatibility.
=> Add custom docker-compose renovate configuration

pkg/api/v1/client_test.go, pkg/api/v1/router.go, pkg/api/v1/router_firmware_test.go
The endpoint `/server-component-firmwares` is incorrectly requesting `server` scopes instead of `server-component-firmwares`. This PR corrects the scopes and add an additional `scopedRealClientTests` test function to help test scoped requests.
=> Fix scopes for server component firmwares

.chainguard/source.yaml
This adds a configuration for Enforce that will accept publicly
verifiable commits from `sigstore.dev` as well as the GPG key from
GitHub Apps.
Enforce already enabled, so remember to [install
`gitsign`](https://github.com/sigstore/gitsign)
and enable it for this repository as follows:
```bash
cd /path/to/my/repository
git config --local commit.gpgsign true  # Sign all commits
git config --local tag.gpgsign true  # Sign all tags
git config --local gpg.x509.program gitsign  # Use gitsign for signing
git config --local gpg.format x509  # gitsign expects x509 args
```
=> Add configuration for Chainguard Enforce

pkg/api/v1/router_server_components_test.go
This resolves #105 where the test case made some assumptions about the fixtures and failed
intermittently.
The change fixes up the `TestIntegrationServerUpdateComponents` test case method to work with components that are present in the fixture data. The earlier revision of this test assumed the first element in the servers, components list is the expected fixture it needs to work with, which is not often the case, since servers, components can be returned in a random order and so the test would fail intermittently.
=> fixes TestIntegrationServerUpdateComponents intermittent failures

README.md
There was a miss close to a code block in the `README.md`
=> [Fix] markdown typos

pkg/api/v1/router_firmware_test.go, pkg/api/v1/router_responses.go
Instead of returning all db errors as 500, return 400s so that the client can differentiate between a server error and a invalid request.
https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1
This prevents clients retrying when the db error not a server side problem.
=> router_responses: return status 400 on duplicate key error

pkg/api/v1/errors.go, pkg/api/v1/requests.go, pkg/api/v1/requests_test.go, pkg/api/v1/router.go, pkg/api/v1/router_firmware_set.go, pkg/api/v1/router_responses.go, pkg/api/v1/router_server.go, pkg/api/v1/router_server_attributes.go, pkg/api/v1/router_server_components.go
This is replaced for a few reasons,
- The JSON stream decoder blocks forever if the server stops sending data
midway in the body, see goroutine dump below [0].
- Switching this to the json.Marshal surfaced issues in implementations where
multiple JSON blocks were being returned in the response to the client,
e.g: `{"foo": "bar"}{"foo": "baz"}`
they are not caught in tests because json.Decoder.Decode doesn't have a problem with those.
- As of now this service does not stream JSON and if the need arises,
the implementation could be switched back to the json.Decoder along
with a for, select loop on the request context.
[0]. Goroutine hung on json.(*Decoder).Decode
```
1 @ 0x43b196 0x44abf2 0x6bf129 0x6be71e 0x46ba21
0x6bf128    net/http.(*http2clientStream).writeRequest+0x9c8 …
```
=> Switch to json.Unmarshal instead of json.Decoder.Decode()

internal/dbtools/fixtures.go, pkg/api/v1/router_server_components.go, pkg/api/v1/router_server_components_test.go
This fixes the case where the component attribute was being added instead
of being updated, which mean't the client received a duplicate key error
for attempting a PUT request to update the component attributes.
=> Components attributes update

db/migrations/00019_firmware_update_constraint.sql, pkg/api/v1/router_firmware_test.go
This changes the firmware uniqueness constraint to include the filename instead of only vendor/component/version as we have cases of vendors distributing firmware for the same component but different models with the same version.
=> Change firmware uniqueness constraint

pkg/api/v1/firmware_list_params.go, pkg/api/v1/router_firmware_test.go
Allows requests to `/server-component-firmwares` to filter on the filename and checksum
=> Add params to ComponentFirmwareVersionListParams

.github/workflows/goreleaser.yml, .goreleaser.yml
goreleaser workflow failed due to deprecated options:
https://github.com/metal-toolbox/hollow-serverservice/actions/runs/5413798979/jobs/9839916270#step:7:18 and https://github.com/metal-toolbox/hollow-serverservice/actions/runs/5413798979/jobs/9839916270#step:7:22
- `--rm-dist` was replaced to `--clean`
- archives.replacements removed on 2023-06-06 (https://goreleaser.com/deprecations/#archivesreplacements)
=> Update goreleaser deprecated options

pkg/api/v1/firmware.go
json tag should be using snake_case to be consistent with the rest of server service structs.
=> ComponentFirmwareVersion json tag to be consistent

pkg/api/v1/router_server_secrets.go, pkg/api/v1/router_server_secrets_test.go
During an upsert of server credentials, if the username changed, it needs to be updated as well.
=> Also update username when credentials are updated

internal/dbtools/fixtures.go, pkg/api/v1/attribute_list_params.go, pkg/api/v1/attribute_list_params_test.go, pkg/api/v1/firmware_set_list_params.go, pkg/api/v1/router_firmware_set_test.go, pkg/api/v1/router_firmware_test.go
This change extends the AttributeListParams to support an Attribute Operator such as - `and` `or`
to enable the client to define how multiple Attributes should be SQL queried.
This change is backwards compatible and defaults to `and` which is the previous behaviour.
The client can now query multiple attributes and specify which of them should looked up
with an OR, by including a `~` separated value - `or` in the `attr` query parameter.
For example, to query firmware sets with models `r6515` OR `r640`,
`/api/v1/server-component-firmware-sets?attr=sh.hollow.firmware_set.labels~model~eq~r6515&attr=sh.hollow.firmware_set.labels~model~eq~r640~or`
=> Attribute operators

README.md
The crdb client is required for running tests and setting up a local docker instance, add a note that helps new users.
cc: Mark Hahn
=> README: add notes on crdb client requirement

go.sum, internal/dbtools/testtools.go, pkg/api/v1/bom.go, pkg/api/v1/router.go, pkg/api/v1/router_bom.go, pkg/api/v1/router_bom_test.go, pkg/api/v1/server_service.go, pkg/api/v1/server_service_test.go
This PR
- adds 2 router handlers for receiving requests and processing Bom upload/fetch(by AocMacAddr): `POST /bom-info/batch-boms-upload`, `GET /bom-info/aoc-mac-address`
- adds 2 client APIs for sending requests to ServerService to upload/fetch Bom(by AocMacAddr): `PostBomXlsx`, `GetBomInfoByAOCMacAddr`.
Not able to resolve the test coverage warning since previous code can guarantee situation won't happen.
However it's still good to leave those checks there in case third party library changes their behavior silently. 
Left few TODOs:
- cleanup rows if failures happens during the middle of the uploading.
- support fetching bom by BmcMacAddr
Also tested with local serverservice + crdb.
=> FS-878 Add bom router handlers and client APIs to upload Boms and fetch Bom(by AocMacAddress)

pkg/api/v1/bom.go, pkg/api/v1/router.go, pkg/api/v1/router_bom.go, pkg/api/v1/router_bom_test.go, pkg/api/v1/server_service.go, pkg/api/v1/server_service_test.go
This PR is a follow up from https://github.com/metal-toolbox/hollow-serverservice/pull/240
Adds a router handlers for receiving requests and processing Bom fetch(by BmcMacAddr): POST GET /bom-info/aoc-mac-address
Adds a client API for sending requests to ServerService to fetch Bom(by BmcMacAddr): GetBomInfoByBMCMacAddr.
Not able to resolve the test coverage warning since previous code can guarantee situation won't happen.
However it's still good to leave those checks there in case third party library changes their behavior silently.
Also tested with local serverservice + crdb.
=> FS-899 Add bom router handlers and client APIs to fetch bom by bmcMacAddree
